stages:
  - build
  - test
  - deploy

Build:
  stage: build
  image:
    name: docker:latest
  services:
    - docker:19-dind
  before_script:
    - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
  script:
    - docker build -t $DOCKER_REGISTRY/gotham-api .
    - docker tag $DOCKER_REGISTRY/gotham-api $DOCKER_REGISTRY/gotham-api:latest
    - docker push $DOCKER_REGISTRY/gotham-api:latest

Deploy:
  stage: deploy
  image:
    name: docker:latest
  services:
    - docker:19-dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install ansible
    - echo -n "$SSH_PRIVATE_KEY" | base64 -d > deploy_key.pem
    - chmod 600 deploy_key.pem
  script:
    - ansible-playbook -i "$INSTANCE_IP," -u ec2-user -i ./deploy_key.pem deploy-playbook.yml
