stages:
  - build
  - test
  - deploy

Build:
  stage: build
  image:
    name: docker:latest
  services:
    - docker:19-dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - docker login --username $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD
  script:
    - docker build -t $DOCKER_REGISTRY/gotham-api .
    - docker tag $DOCKER_REGISTRY/gotham-api:latest
    - docker push $DOCKER_REGISTRY/gotham-api:latest

Deploy:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: ["/bin/sh", "-c"]
  dependencies:
    - Build
  before_script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  script:
    - aws ssm send-command --document-name "AWS-RunShellScript" --instance-ids "$INSTANCE_ID" --parameters '{"commands":["#!/bin/bash","cd /home/ec2-user","sudo docker-compose down","sudo docker image rm -f $DOCKER_REGISTRY/gotham-api","sudo docker-compose up"]}'
